name = "mentalhealth"
main = "worker.js"
compatibility_date = "2024-02-13"

# Exclude files yang tidak perlu
exclude_files = [
  ".git*",
  "*.md",
  "node_modules/**",
  "test/**",
  "gradle/**",
  "app/build/**",
  "*.properties",
  "*.bat",
  "*.jar",
  "*.toml",
  "*.yaml",
  "*.yml"
]

[env.production]
routes = ["4211421036.github.io/MentalHealth/*"]
